// ─────────────────────────────────────────────────────────────────────────────
// Keyword dictionaries for deterministic prompt interpretation
// Edit these to expand recognition without touching interpreter logic.
// ─────────────────────────────────────────────────────────────────────────────

export const MOOD_TERMS: Record<string, string> = {
  warm: "warm",
  cozy: "warm",
  cosy: "warm",
  inviting: "warm",
  welcoming: "warm",
  homey: "warm",
  calm: "calm",
  serene: "calm",
  peaceful: "calm",
  tranquil: "calm",
  quiet: "calm",
  still: "calm",
  soothing: "calm",
  relaxed: "calm",
  gentle: "calm",
  energetic: "energetic",
  vibrant: "energetic",
  dynamic: "energetic",
  bold: "energetic",
  lively: "energetic",
  intense: "dramatic",
  fierce: "energetic",
  powerful: "powerful",
  raw: "raw",
  unfiltered: "raw",
  serious: "serious",
  professional: "serious",
  formal: "serious",
  corporate: "serious",
  authoritative: "serious",
  polished: "sophisticated",
  playful: "playful",
  fun: "playful",
  whimsical: "playful",
  cheerful: "playful",
  lighthearted: "playful",
  quirky: "playful",
  dark: "dark",
  moody: "dark",
  dramatic: "dramatic",
  gritty: "gritty",
  haunting: "haunting",
  eerie: "haunting",
  mysterious: "mysterious",
  enigmatic: "mysterious",
  cryptic: "mysterious",
  uncanny: "mysterious",
  noir: "dark",
  brooding: "dark",
  melancholic: "melancholic",
  melancholy: "melancholic",
  somber: "melancholic",
  sorrowful: "melancholic",
  bittersweet: "melancholic",
  contemplative: "contemplative",
  reflective: "contemplative",
  meditative: "contemplative",
  thoughtful: "contemplative",
  rebellious: "rebellious",
  defiant: "rebellious",
  punk: "rebellious",
  edgy: "edgy",
  provocative: "edgy",
  confident: "confident",
  assertive: "confident",
  fearless: "confident",
  bright: "bright",
  light: "bright",
  airy: "bright",
  fresh: "bright",
  luminous: "bright",
  sunny: "bright",
  crisp: "bright",
  nostalgic: "nostalgic",
  retro: "nostalgic",
  vintage: "nostalgic",
  throwback: "nostalgic",
  romantic: "romantic",
  elegant: "elegant",
  graceful: "elegant",
  luxurious: "luxurious",
  opulent: "luxurious",
  premium: "luxurious",
  soft: "soft",
  dreamy: "dreamy",
  intimate: "intimate",
  tender: "tender",
  sensual: "sensual",
  sensuous: "sensual",
  seductive: "sensual",
  sophisticated: "sophisticated",
  refined: "sophisticated",
  "awe inspiring": "awe-inspiring",
  "awe-inspiring": "awe-inspiring",
  awe: "awe-inspiring",
  awesome: "awe-inspiring",
  inspiring: "inspiring",
  inspirational: "inspiring",
  inspiration: "inspiring",
  wonder: "wonder",
  wondrous: "wonder",
  amazing: "awe-inspiring",
  astonishing: "awe-inspiring",
  extraordinary: "awe-inspiring",
  impressive: "awe-inspiring",
  magnificent: "majestic",
  breathtaking: "breathtaking",
  spectacular: "breathtaking",
  stunning: "breathtaking",
  uplifting: "uplifting",
  elevating: "uplifting",
  hopeful: "hopeful",
  optimistic: "hopeful",
  aspirational: "aspirational",
  empowering: "empowering",
  stirring: "inspiring",
  moving: "inspiring",
  visionary: "visionary",
  epic: "epic",
  grand: "grand",
  grandeur: "grand",
  monumental: "grand",
  majestic: "majestic",
  sublime: "sublime",
  transcendent: "transcendent",
  transcendental: "transcendent",
  striking: "striking",
  impactful: "powerful",
  forceful: "powerful",
  exhilarating: "energetic",
  thrilling: "energetic",
  enchanting: "enchanting",
  magical: "enchanting",
  ethereal: "ethereal",
  mystical: "ethereal",
  radiant: "radiant",
  glowing: "radiant",
  celebratory: "celebratory",
  joyful: "joyful",
  delighted: "joyful",
  futuristic: "futuristic",
  innovative: "futuristic",
  advanced: "futuristic",
  digital: "futuristic",
  organic: "organic",
  natural: "organic",
  earthy: "earthy",
  grounded: "grounded",
  authentic: "authentic",
  honest: "authentic",
  genuine: "authentic",
};

/**
 * Related mood signals derived from a directly stated emotional direction.
 * These are intentionally bounded: they broaden the search space without
 * turning a short brief into an unrelated list of adjectives.
 */
export const MOOD_EXPANSIONS: Record<string, string[]> = {
  mysterious: ["haunting", "dark"],
  haunting: ["mysterious", "dark"],
  melancholic: ["nostalgic", "contemplative", "soft"],
  contemplative: ["calm", "melancholic"],
  gritty: ["raw", "edgy", "rebellious"],
  raw: ["gritty", "authentic", "rebellious"],
  rebellious: ["edgy", "confident", "raw"],
  edgy: ["rebellious", "striking", "gritty"],
  confident: ["powerful", "empowering", "striking"],
  romantic: ["intimate", "dreamy", "tender"],
  elegant: ["sophisticated", "refined"],
  luxurious: ["elegant", "sophisticated", "sensual"],
  sophisticated: ["elegant", "refined", "serious"],
  soft: ["tender", "dreamy", "intimate"],
  dreamy: ["ethereal", "soft", "enchanting"],
  intimate: ["tender", "soft", "romantic"],
  tender: ["intimate", "soft", "romantic"],
  sensual: ["romantic", "intimate", "luxurious"],
  futuristic: ["visionary", "confident", "striking"],
  organic: ["grounded", "authentic", "earthy"],
  earthy: ["organic", "grounded", "warm"],
  grounded: ["organic", "authentic", "calm"],
  authentic: ["grounded", "raw", "organic"],
  joyful: ["celebratory", "playful", "radiant"],
  celebratory: ["radiant", "uplifting", "energetic"],
  "awe-inspiring": ["wonder", "uplifting", "epic", "majestic", "breathtaking"],
  inspiring: ["uplifting", "hopeful", "aspirational", "empowering"],
  wonder: ["awe-inspiring", "enchanting", "sublime"],
  uplifting: ["hopeful", "radiant", "celebratory"],
  hopeful: ["uplifting", "aspirational", "radiant"],
  aspirational: ["inspiring", "visionary", "empowering"],
  empowering: ["inspiring", "powerful", "aspirational"],
  visionary: ["aspirational", "inspiring", "epic"],
  epic: ["grand", "majestic", "powerful", "dramatic"],
  grand: ["majestic", "epic"],
  majestic: ["grand", "sublime", "powerful"],
  breathtaking: ["awe-inspiring", "striking", "sublime"],
  sublime: ["transcendent", "ethereal", "wonder"],
  transcendent: ["sublime", "ethereal", "visionary"],
  dramatic: ["striking", "powerful"],
  powerful: ["empowering", "striking"],
  enchanting: ["ethereal", "wonder"],
  ethereal: ["sublime", "enchanting", "radiant"],
  radiant: ["uplifting", "hopeful", "celebratory"],
};

export const STYLE_TERMS: Record<string, string> = {
  editorial: "editorial",
  journalistic: "editorial",
  magazine: "editorial",
  documentary: "editorial",
  reportage: "editorial",
  minimalist: "minimalist",
  minimal: "minimalist",
  clean: "minimalist",
  simple: "minimalist",
  sparse: "minimalist",
  stripped: "minimalist",
  experimental: "experimental",
  avant: "experimental",
  abstract: "experimental",
  unconventional: "experimental",
  surreal: "experimental",
  retro: "retro",
  vintage: "retro",
  "old-school": "retro",
  "old school": "retro",
  handmade: "handmade",
  organic: "handmade",
  crafted: "handmade",
  artisan: "handmade",
  illustrative: "illustrative",
  illustrated: "illustrative",
  drawn: "illustrative",
  painted: "illustrative",
  sketch: "illustrative",
  typographic: "typographic",
  type: "typographic",
  lettering: "typographic",
  calligraphy: "typographic",
  photographic: "photographic",
  photo: "photographic",
  realistic: "photographic",
  candid: "photographic",
  cinematic: "cinematic",
  geometric: "geometric",
  grid: "geometric",
  structured: "geometric",
  architectural: "geometric",
  symmetrical: "geometric",
};

export const AUDIENCE_TERMS: Record<string, string> = {
  "young adults": "young adults",
  youth: "young adults",
  millennials: "young adults",
  "gen z": "young adults",
  teenagers: "young adults",
  teens: "young adults",
  children: "children",
  kids: "children",
  seniors: "seniors",
  elderly: "seniors",
  professionals: "professionals",
  business: "professionals",
  corporate: "professionals",
  community: "community",
  local: "community",
  neighborhood: "community",
  families: "families",
  parents: "families",
  students: "students",
  designers: "designers",
  creatives: "designers",
  consumers: "consumers",
  shoppers: "consumers",
  fans: "fans",
  enthusiasts: "enthusiasts",
  athletes: "athletes",
};

export const SUBJECT_TERMS: Record<string, string> = {
  food: "food",
  cuisine: "food",
  restaurant: "food",
  cooking: "food",
  meal: "food",
  drink: "food",
  beverage: "food",
  cafe: "food",
  coffee: "food",
  market: "food",
  people: "people",
  person: "people",
  portrait: "people",
  human: "people",
  girl: "people",
  woman: "people",
  boy: "people",
  man: "people",
  child: "people",
  faces: "people",
  face: "people",
  crowd: "people",
  character: "people",
  figure: "people",
  architecture: "architecture",
  building: "architecture",
  urban: "architecture",
  city: "architecture",
  interior: "architecture",
  room: "architecture",
  structure: "architecture",
  nature: "nature",
  landscape: "nature",
  outdoors: "nature",
  plants: "nature",
  botanical: "nature",
  forest: "nature",
  ocean: "nature",
  mountain: "nature",
  sky: "nature",
  water: "nature",
  floral: "nature",
  flower: "nature",
  products: "products",
  product: "products",
  packaging: "products",
  brand: "products",
  object: "products",
  "still life": "products",
  fashion: "fashion",
  clothing: "fashion",
  apparel: "fashion",
  outfit: "fashion",
  wear: "fashion",
  music: "music",
  concert: "music",
  band: "music",
  album: "music",
  art: "art",
  painting: "art",
  illustration: "art",
  gallery: "art",
  exhibition: "art",
  technology: "technology",
  tech: "technology",
  digital: "technology",
  device: "technology",
  travel: "travel",
  destination: "travel",
  journey: "travel",
  adventure: "travel",
  culture: "culture",
  community: "culture",
  tradition: "culture",
  festival: "culture",
  sport: "sport",
  sports: "sport",
  athletic: "sport",
  fitness: "sport",
  health: "health",
  wellness: "health",
};

export const COLOR_DIRECTION_TERMS: Record<string, string> = {
  warm: "warm",
  orange: "warm",
  red: "warm",
  amber: "warm",
  golden: "warm",
  earthy: "warm",
  terracotta: "warm",
  coral: "warm",
  rust: "warm",
  cool: "cool",
  blue: "cool",
  teal: "cool",
  cyan: "cool",
  green: "cool",
  indigo: "cool",
  slate: "cool",
  muted: "muted",
  desaturated: "muted",
  dusty: "muted",
  faded: "muted",
  washed: "muted",
  neutral: "muted",
  vibrant: "vibrant",
  saturated: "vibrant",
  colorful: "vibrant",
  bright: "vibrant",
  bold: "vibrant",
  neon: "vibrant",
  monochrome: "monochrome",
  black: "monochrome",
  white: "monochrome",
  grayscale: "monochrome",
  grey: "monochrome",
  gray: "monochrome",
  "black and white": "monochrome",
  pastel: "pastel",
  soft: "pastel",
  light: "pastel",
  pale: "pastel",
  delicate: "pastel",
};

export const FORMAT_TERMS: Record<string, string> = {
  poster: "poster",
  flyer: "poster",
  billboard: "poster",
  banner: "poster",
  logo: "logo",
  brand: "logo",
  mark: "logo",
  icon: "logo",
  website: "website",
  web: "website",
  landing: "website",
  digital: "website",
  app: "website",
  social: "social",
  instagram: "social",
  facebook: "social",
  twitter: "social",
  tiktok: "social",
  reel: "social",
  post: "social",
  editorial: "editorial",
  magazine: "editorial",
  book: "editorial",
  spread: "editorial",
  layout: "editorial",
  print: "print",
  brochure: "print",
  catalogue: "print",
  catalog: "print",
  screen: "screen",
  display: "screen",
  ui: "screen",
  interface: "screen",
  branding: "branding",
  identity: "branding",
  campaign: "branding",
};

export const COMPOSITION_TERMS: Record<string, string> = {
  centered: "centered",
  central: "centered",
  symmetric: "centered",
  asymmetrical: "asymmetrical",
  asymmetric: "asymmetrical",
  off: "asymmetrical",
  dense: "dense",
  packed: "dense",
  busy: "dense",
  spacious: "spacious",
  whitespace: "spacious",
  minimal: "spacious",
  airy: "spacious",
  portrait: "portrait",
  vertical: "portrait",
  tall: "portrait",
  landscape: "landscape",
  horizontal: "landscape",
  wide: "landscape",
};

export const POSE_TERMS: Record<string, string> = {
  standing: "standing",
  seated: "seated",
  sitting: "seated",
  crouching: "crouching",
  kneeling: "kneeling",
  walking: "walking",
  running: "running",
  dancing: "dancing",
  reaching: "reaching",
  holding: "holding",
  leaning: "leaning",
  lying: "lying down",
  reclining: "reclining",
  profile: "profile pose",
  "full body": "full-body pose",
  gesture: "expressive gesture",
};

export const LIGHTING_TERMS: Record<string, string> = {
  daylight: "daylight",
  sunlight: "sunlight",
  sunny: "sunlight",
  night: "night lighting",
  nighttime: "night lighting",
  moonlight: "moonlight",
  moonlit: "moonlight",
  backlit: "backlighting",
  silhouette: "silhouette lighting",
  spotlight: "spotlight",
  rimlight: "rim lighting",
  "rim light": "rim lighting",
  neon: "neon lighting",
  candlelight: "candlelight",
  shadowy: "shadowy lighting",
  "low-key": "low-key lighting",
  "low key": "low-key lighting",
  "high-key": "high-key lighting",
  "high key": "high-key lighting",
  diffused: "diffused lighting",
  diffuse: "diffused lighting",
  hard: "hard lighting",
  softbox: "soft lighting",
};

export const MATERIAL_TERMS: Record<string, string> = {
  wood: "wood",
  wooden: "wood",
  metal: "metal",
  metallic: "metal",
  glass: "glass",
  ceramic: "ceramic",
  clay: "clay",
  stone: "stone",
  concrete: "concrete",
  paper: "paper",
  cardboard: "cardboard",
  fabric: "fabric",
  textile: "fabric",
  denim: "denim",
  leather: "leather",
  plastic: "plastic",
  silk: "silk",
  fur: "fur",
  glossy: "glossy surface",
  matte: "matte surface",
  rough: "rough texture",
  smooth: "smooth texture",
  tactile: "tactile texture",
  grainy: "grainy texture",
  textured: "visible texture",
};

// Conflicting term pairs — if both appear, flag as ambiguity
export const CONFLICTING_PAIRS: [string[], string[]][] = [
  [["playful", "fun", "whimsical"], ["serious", "formal", "professional", "corporate"]],
  [["warm"], ["cool"]],
  [["dark", "moody"], ["bright", "light", "airy"]],
  [["minimalist", "minimal", "clean"], ["dense", "busy", "packed"]],
  [["vibrant", "colorful"], ["muted", "desaturated", "grayscale", "monochrome"]],
];
