// ─────────────────────────────────────────────────────────────────────────────
// Keyword dictionaries for deterministic prompt interpretation
// Edit these to expand recognition without touching interpreter logic.
// ─────────────────────────────────────────────────────────────────────────────

export const MOOD_TERMS: Record<string, string> = {
  warm: "warm",
  cozy: "warm",
  inviting: "warm",
  calm: "calm",
  serene: "calm",
  peaceful: "calm",
  tranquil: "calm",
  energetic: "energetic",
  vibrant: "energetic",
  dynamic: "energetic",
  bold: "energetic",
  serious: "serious",
  professional: "serious",
  formal: "serious",
  corporate: "serious",
  playful: "playful",
  fun: "playful",
  whimsical: "playful",
  cheerful: "playful",
  dark: "dark",
  moody: "dark",
  dramatic: "dark",
  gritty: "dark",
  bright: "bright",
  light: "bright",
  airy: "bright",
  fresh: "bright",
  nostalgic: "nostalgic",
  retro: "nostalgic",
  vintage: "nostalgic",
  romantic: "romantic",
  elegant: "romantic",
  luxurious: "romantic",
};

export const STYLE_TERMS: Record<string, string> = {
  editorial: "editorial",
  journalistic: "editorial",
  magazine: "editorial",
  minimalist: "minimalist",
  minimal: "minimalist",
  clean: "minimalist",
  simple: "minimalist",
  experimental: "experimental",
  avant: "experimental",
  abstract: "experimental",
  retro: "retro",
  vintage: "retro",
  "old-school": "retro",
  handmade: "handmade",
  organic: "handmade",
  crafted: "handmade",
  illustrative: "illustrative",
  illustrated: "illustrative",
  drawn: "illustrative",
  typographic: "typographic",
  type: "typographic",
  lettering: "typographic",
  photographic: "photographic",
  photo: "photographic",
  realistic: "photographic",
  geometric: "geometric",
  grid: "geometric",
  structured: "geometric",
};

export const AUDIENCE_TERMS: Record<string, string> = {
  "young adults": "young adults",
  youth: "young adults",
  millennials: "young adults",
  "gen z": "young adults",
  teenagers: "young adults",
  teens: "young adults",
  children: "children",
  kids: "children",
  seniors: "seniors",
  elderly: "seniors",
  professionals: "professionals",
  business: "professionals",
  corporate: "professionals",
  community: "community",
  local: "community",
  neighborhood: "community",
  families: "families",
  parents: "families",
  students: "students",
  designers: "designers",
  creatives: "designers",
};

export const SUBJECT_TERMS: Record<string, string> = {
  food: "food",
  cuisine: "food",
  restaurant: "food",
  cooking: "food",
  meal: "food",
  people: "people",
  person: "people",
  portrait: "people",
  human: "people",
  faces: "people",
  architecture: "architecture",
  building: "architecture",
  urban: "architecture",
  city: "architecture",
  nature: "nature",
  landscape: "nature",
  outdoors: "nature",
  plants: "nature",
  botanical: "nature",
  products: "products",
  product: "products",
  packaging: "products",
  brand: "products",
  fashion: "fashion",
  clothing: "fashion",
  apparel: "fashion",
  music: "music",
  concert: "music",
  art: "art",
  painting: "art",
  illustration: "art",
  technology: "technology",
  tech: "technology",
  digital: "technology",
  travel: "travel",
  destination: "travel",
  culture: "culture",
  community: "culture",
};

export const COLOR_DIRECTION_TERMS: Record<string, string> = {
  warm: "warm",
  orange: "warm",
  red: "warm",
  amber: "warm",
  golden: "warm",
  earthy: "warm",
  cool: "cool",
  blue: "cool",
  teal: "cool",
  cyan: "cool",
  green: "cool",
  muted: "muted",
  desaturated: "muted",
  dusty: "muted",
  faded: "muted",
  vibrant: "vibrant",
  saturated: "vibrant",
  colorful: "vibrant",
  bright: "vibrant",
  monochrome: "monochrome",
  black: "monochrome",
  white: "monochrome",
  grayscale: "monochrome",
  grey: "monochrome",
  gray: "monochrome",
  pastel: "pastel",
  soft: "pastel",
  light: "pastel",
};

export const FORMAT_TERMS: Record<string, string> = {
  poster: "poster",
  flyer: "poster",
  billboard: "poster",
  logo: "logo",
  brand: "logo",
  mark: "logo",
  website: "website",
  web: "website",
  landing: "website",
  digital: "website",
  social: "social",
  instagram: "social",
  facebook: "social",
  twitter: "social",
  editorial: "editorial",
  magazine: "editorial",
  book: "editorial",
  print: "print",
  brochure: "print",
  banner: "print",
  screen: "screen",
  display: "screen",
  ui: "screen",
};

export const COMPOSITION_TERMS: Record<string, string> = {
  centered: "centered",
  central: "centered",
  symmetric: "centered",
  asymmetrical: "asymmetrical",
  asymmetric: "asymmetrical",
  off: "asymmetrical",
  dense: "dense",
  packed: "dense",
  busy: "dense",
  spacious: "spacious",
  whitespace: "spacious",
  minimal: "spacious",
  airy: "spacious",
  portrait: "portrait",
  vertical: "portrait",
  tall: "portrait",
  landscape: "landscape",
  horizontal: "landscape",
  wide: "landscape",
};

// Conflicting term pairs — if both appear, flag as ambiguity
export const CONFLICTING_PAIRS: [string[], string[]][] = [
  [["playful", "fun", "whimsical"], ["serious", "formal", "professional", "corporate"]],
  [["warm"], ["cool"]],
  [["dark", "moody"], ["bright", "light", "airy"]],
  [["minimalist", "minimal", "clean"], ["dense", "busy", "packed"]],
  [["vibrant", "colorful"], ["muted", "desaturated", "grayscale", "monochrome"]],
];
